.\" -*-nroff-*-
.\"
.\" pgmtovol
.TH PGMTOVOL 1 2006-07
.SH NAME
pgmtovol \- Convert a series of PGM images to volume data
.SH SYNOPSIS
pgmtovol
.SH DESCRIPTION
pgmtovol reads a series of PGM images from standard input, converts 
them to volume data in the .vol format, and writes this data to
standard output.
.br
This program has no options.
.br
The .vol data format is specified at 
http://www.cb.uu.se/~tc18/code_data_set/Code/Libvol/.
.SH AUTHORS
pgmtovol was written by Martin Lambers <marlam@marlam.de>.
