.\" -*-nroff-*-
.\"
.\" voltopgm
.TH PGMTOVOL 1 2006-07
.SH NAME
voltopgm \- Convert volume data to a series of PGM images
.SH SYNOPSIS
voltopgm
.SH DESCRIPTION
voltopgm reads volume data in the .vol format from standard input, converts it
to a series of PGM images, and writes these images to standard output.
.br
This program has no options.
.br
The .vol data format is specified at 
http://www.cb.uu.se/~tc18/code_data_set/Code/Libvol/.
.SH AUTHORS
voltopgm was written by Martin Lambers <marlam@marlam.de>.
