.\" -*-nroff-*-
.\"
.TH CVLVIEW 1 2010-03
.SH NAME
CVLView \- A data viewer.
.SH SYNOPSIS
.B cvlview
.SH DESCRIPTION
CVLView is a viewer for arbritrary data that is stored in pfs files.
.br
The program's homepage is <http://cvtool.sourceforge.net/cvlview.html>.
.SH AUTHORS
Martin Lambers <marlam@marlam.de>.
.SH SEE ALSO
.BR pfsview (1)
.BR pfsglview (1)
