.\" -*-nroff-*-
.\"
.TH CVLTONEMAP 1 2008-01
.SH NAME
CVLTonemap \- A HDR image viewer and tone mapping tool
.SH SYNOPSIS
.B cvltonemap
.SH DESCRIPTION
CVLTonemap is an interactive HDR image viewer and tone mapping tool based on
the CVL library.
.br
The program's homepage is <http://cvtool.sourceforge.net/cvltonemap.html>.
.SH AUTHORS
Martin Lambers <marlam@marlam.de>.
.SH SEE ALSO
.BR pfsview (1)
.BR pfsglview (1)
