\input texinfo   @c -*-texinfo-*-
@afourpaper
@setfilename cvl.info
@set UPDATED December 8, 2006
@set UPDATED-MONTH December 2006
@set EDITION 0.1.1
@set VERSION 0.1.1
@settitle CVL @value{VERSION}

@c Define new indices: for options (op) and commands (cm)
@defcodeindex op
@defcodeindex cm

@finalout
@copying
This manual was last updated @value{UPDATED} for version
@value{VERSION} of CVL.

Copyright @copyright{} 2005, 2006 Martin Lambers

@quotation
This program, including this manual, is free software; you can redistribute it
and/or modify it under the terms of the GNU General Public License as published
by the Free Software Foundation; either version 2 of the License, or (at your
option) any later version.

This program, including this manual, is distributed in the hope that it will be
useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
Public License for more details.

You should have received a copy of the GNU General Public License along with
this program and manual; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
@end quotation
@end copying

@dircategory Individual utilities
@direntry
* CVL: (CVL).	A computer vision library.
@end direntry

@titlepage
@title CVL
@subtitle A computer vision library
@subtitle version @value{VERSION}, @value{UPDATED}
@author Martin Lambers (@email{marlam@@marlam.de})
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top CVL
@insertcopying
@end ifnottex

@menu
* Using CVL::
* Concepts and overview::
* API reference::
* Enhancing CVL::
@end menu


@node Using CVL
@chapter Using CVL

Include the header file @code{<cvl/cvl.h>} in your programs:
@example
#include <cvl/cvl.h>
@end example

Then compile and link your program with the appropriate flags, similar to this:
@example
cc -I/usr/include/cairo -o myprog myprog.c -lcvl
@end example
(The @code{-I} option is necessary to find the headers of the CAIRO graphics library.)

If your project uses the GNU autotools, you can use the following
in @code{configure.ac} to search for e.g. CVL >= 1.2.10 and set @code{CPPFLAGS},
@code{HAVE_LIBCVL}, @code{LIBCVL} and @code{LTLIBCVL} (if you use libtool) automatically:
@example
AM_LIBCVL([0x01020a], [], [AC_MSG_ERROR([Cannot find required version of CVL.])])
@end example
You need to copy the @code{cvl.m4} file into your project, along with the following
three prerequisites: @code{config.rpath}, @code{lib-link.m4}, and @code{absolute-header.m4}. 
All three are provided by gnulib @url{http://www.gnu.org/software/gnulib/}. 
You can download the files directly from the gnulib CVS repository 
@url{http://cvs.savannah.gnu.org/viewcvs/gnulib/gnulib/}.


@node Concepts and overview
@chapter Concepts and overview

TODO


@node API reference
@chapter API reference

The API reference is provided in HTML format in the separate directory 
@code{cvl-reference}.


@node Enhancing CVL
@chapter Enhancing CVL

TODO


@bye
