.\" -*-nroff-*-
.\"
.TH CVTOOL 1 2006-07
.SH NAME
cvtool \- a computer vision tool
.SH SYNOPSIS
.B cvtool 
[-q|--quiet] [-v|--verbose] <command> [option...]
.SH DESCRIPTION
Cvtool is a filter that manipulates one or more images: it reads images from
standard input and writes the manipulated images to standard output. It can
read and write streams of NetPBM images (ppm, pgm, pbm) and video streams in
the YUV4MPEG2 format used by the MJPEG Tools.
.PP
Cvtool integrates all its functionality into a single binary, and makes
it available through commands such as \fBrotate\fP, \fBfilter\fP, and 
others.
.PP
\fBcvtool help\fP prints a list of available commands, and
\fBcvtool help\fP \fIcmd\fP prints help for the command \fIcmd\fP.
.PP
The full documentation is maintained as a Texinfo manual, available in
different formats.  The program's homepage is http://cvtool.sourceforge.net/.
.SH AUTHORS
Cvtool was written by Martin Lambers.
.br
Other authors are listed in the AUTHORS file in the source distribution.
.SH SEE ALSO
.BR netpbm (1), 
.BR mjpegtools (1),
.BR y4mscaler (1),
.BR mogrify (1)
