.\" -*-nroff-*-
.\"
.TH CVTOOL 1 2010-03
.SH NAME
cvtool \- a computer vision tool
.SH SYNOPSIS
.B cvtool 
[-q|--quiet] [-v|--verbose] <command> [option...]
.SH DESCRIPTION
Cvtool is a filter that manipulates one or more images (called frames): it
reads frames from standard input and writes the manipulated frames to standard
output. It can read and write streams of frames in PNM (ppm, pgm, pbm, pnm,
pam) or PFS format.
.PP
Cvtool integrates all its functionality into a single binary, and makes
it available through commands such as \fBrotate\fP, \fBfilter\fP, and 
others.
.PP
"\fBcvtool help\fP" prints a list of available commands, and
"\fBcvtool help\fP \fIcmd\fP" prints help for the command \fIcmd\fP.
.PP
The full documentation is maintained as a Texinfo manual, available in
different formats. The program's homepage is https://marlam.de/cvl.
.SH AUTHORS
Cvtool was written by Martin Lambers <marlam@marlam.de>.
.br
Other authors are listed in the AUTHORS file in the source distribution.
.SH SEE ALSO
.BR netpbm (1), 
.BR pfsview (1)
